blank_issues_enabled: false
contact_links:
  - name: Readme
    url: https://github.com/corepass/auth#readme
    about: Read more about the code
  - name: CorePass
    url: https://corepass.net
    about: Get information about CorePass
